services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 20s
      retries: 10
    networks:
      - springboot-mysql-net

  spring-boot-app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart:
      on-failure
    ports:
      - '8080:8080'
    depends_on:
      mysql:
       condition: service_healthy

    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net:
    driver: bridge